# Project: P587
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = tempparm.o
LINKOBJ  = tempparm.o
LIBS     = -L"E:/Program/Dev-Cpp/MinGW64/lib" -L"E:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Program/Dev-Cpp/MinGW64/include" -I"E:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Program/Dev-Cpp/MinGW64/include" -I"E:/Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Program/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = P587.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

tempparm.o: tempparm.cpp
	$(CPP) -c tempparm.cpp -o tempparm.o $(CXXFLAGS)
